version: '3'
services:
  database:
    image: postgres:14.3-alpine
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=rubyapi
    healthcheck:
      test: ["pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://search:9200
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:5601/api/status || exit 1" ]
      interval: 5s
      timeout: 3s
    depends_on:
      search:
        condition: service_healthy

  cache:
    image: redis:7-alpine
    ports:
    - "6381:6381"
    healthcheck:
      test: ["redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  session:
    image: redis:7-alpine
    command:
    - "--maxmemory-policy noeviction"
    ports:
    - "6380:6380"
    healthcheck:
      test: ["redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:9200/_cluster/health?wait_for_status=green&timeout=1s || exit 1 " ]
      retries: 3
      interval: 5s
      timeout: 3s
