development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_SESSION_URL") { "redis://localhost:6381/1" } %>
  channel_prefix: rubyapi_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
