name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Test"]
    types: ["completed"]
    branches: ["main"]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

concurrency: production_deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions@1.4
        with:
          args: "deploy --app rubyapi --wait-timeout 180 -e GIT_SHA=$GITHUB_SHA"
