name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

concurrency: production_deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup pack command
        uses: buildpacks/github-actions/setup-pack@v5.3.0

      - name: Build application image
        run: pack build rubyapi --path . --builder heroku/builder:22 --tag ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      - name: Inspect application image
        run: pack inspect-image rubyapi

      - name: Push Image
        run: docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
