name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - "**.md"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "npm"

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: npm ci

      - name: Run Ruby linting
        run: bin/standardrb --no-fix

      - name: Run Typescript Linting
        run: npm run lint

  test-import:
    runs-on: ubuntu-latest
    services:
      search:
        image: opensearchproject/opensearch:2.11.0
        ports:
          - 9200:9200
        env:
          "discovery.type": "single-node"
          "plugins.security.disabled": "true"
        options: >-
          --health-cmd "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"
          --health-start-period 30s
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Test Importing Ruby Documentation
        env:
          SEARCH_URL: "http://localhost:9200"
        run: bin/rails "import:ruby[3.4]"

  test:
    runs-on: ubuntu-latest
    services:
      search:
        image: opensearchproject/opensearch:2.11.0
        ports:
          - 9200:9200
        env:
          "discovery.type": "single-node"
          "plugins.security.disabled": "true"
        options: >-
          --health-cmd "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"
          --health-start-period 30s
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: |
          npm run build && npm run build:css
          bin/rails test

  test-system:
    runs-on: ubuntu-latest
    services:
      search:
        image: opensearchproject/opensearch:2.11.0
        ports:
          - 9200:9200
        env:
          "discovery.type": "single-node"
          "plugins.security.disabled": "true"
        options: >-
          --health-cmd "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"
          --health-start-period 30s
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: |
          npm run build && npm run build:css
          bin/rails test:system
